export const works = [
  {
    id: 'work.0.id',
    image: 'work.0.image',
    title: 'work.0.title',
    company: 'work.0.company',
    type: 'work.0.type',
    description: 'work.0.description',
    startDate: 'work.0.startDate',
    endDate: 'work.0.endDate',
    services: [
      'work.0.services.0',
      'work.0.services.1',
      'work.0.services.2',
      'work.0.services.3',
    ],
    stack: [
      'work.0.stack.0',
      'work.0.stack.1',
      'work.0.stack.2',
      'work.0.stack.3',
      'work.0.stack.4',
      'work.0.stack.5',
    ],
    challenge: 'work.0.challenge',
    goal: 'work.0.goal',
    result: 'work.0.result',
  },
  {
    id: 'work.1.id',
    image: 'work.1.image',
    title: 'work.1.title',
    company: 'work.1.company',
    type: 'work.1.type',
    description: 'work.1.description',
    startDate: 'work.1.startDate',
    endDate: 'work.1.endDate',
    services: [
      'work.1.services.0',
      'work.1.services.1',
      'work.1.services.2',
      'work.1.services.3',
    ],
    stack: [
      'work.1.stack.0',
      'work.1.stack.1',
      'work.1.stack.2',
      'work.1.stack.3',
      'work.1.stack.4',
      'work.1.stack.5',
    ],
    challenge: 'work.1.challenge',
    goal: 'work.1.goal',
    result: 'work.1.result',
  },
  {
    id: 'work.2.id',
    image: 'work.2.image',
    title: 'work.2.title',
    company: 'work.2.company',
    type: 'work.2.type',
    description: 'work.2.description',
    startDate: 'work.2.startDate',
    endDate: 'work.2.endDate',
    stack: [
      'work.2.stack.0',
      'work.2.stack.1',
      'work.2.stack.2',
      'work.2.stack.3',
      'work.2.stack.4',
      'work.2.stack.5',
      'work.2.stack.6',
    ],
    services: ['work.2.services.0', 'work.2.services.1'],
    challenge: 'work.2.challenge',
    goal: 'work.2.goal',
    result: 'work.2.result',
  },
  {
    id: 'work.3.id',
    image: 'work.3.image',
    title: 'work.3.title',
    company: 'work.3.company',
    type: 'work.3.type',
    description: 'work.3.description',
    startDate: 'work.3.startDate',
    endDate: 'work.3.endDate',
    stack: [
      'work.3.stack.0',
      'work.3.stack.1',
      'work.3.stack.2',
      'work.3.stack.3',
      'work.3.stack.4',
    ],
    services: [
      'work.3.services.0',
      'work.3.services.1',
      'work.3.services.2',
      'work.3.services.3',
    ],
    challenge: 'work.3.challenge',
    goal: 'work.3.goal',
    result: 'work.3.result',
  },
];

export const skills = [
  {
    index: '01',
    titleKey: 'skills.0.title',
    descriptionKey: 'skills.0.description',
  },
  {
    index: '02',
    titleKey: 'skills.1.title',
    descriptionKey: 'skills.1.description',
  },
  {
    index: '03',
    titleKey: 'skills.2.title',
    descriptionKey: 'skills.2.description',
  },
];

export const education = [
  {
    title: 'education.0.title',
    location: 'education.0.location',
    date: 'education.0.date',
    description: 'education.0.description',
  },
  {
    title: 'education.1.title',
    location: 'education.1.location',
    date: 'education.1.date',
    description: 'education.1.description',
  },
  {
    title: 'education.2.title',
    location: 'education.2.location',
    date: 'education.2.date',
    description: 'education.2.description',
  },
];

export const steps = [
  {
    title: 'steps.0.title',
    subtitle: 'steps.0.subtitle',
    date: 'steps.0.date',
    description: 'steps.0.description',
  },
  {
    title: 'steps.1.title',
    subtitle: 'steps.1.subtitle',
    date: 'steps.1.date',
    description: 'steps.1.description',
  },
  {
    title: 'steps.2.title',
    subtitle: 'steps.2.subtitle',
    date: 'steps.2.date',
    description: 'steps.2.description',
  },
  {
    title: 'steps.3.title',
    subtitle: 'steps.3.subtitle',
    date: 'steps.3.date',
    description: 'steps.3.description',
  },
  {
    title: 'steps.4.title',
    subtitle: 'steps.4.subtitle',
    date: 'steps.4.date',
    description: 'steps.4.description',
  },
];
